### ISSUE TITLE
ML - MileStone 1 - Creating the first classifier, real-estate and building utilities

### ISSUE THREAD

**Issue by io-commits** [Immanuelbh/HebrewCourtVerdictsAnalyzer#11]
ML 

- [x] - convert json to csv
- [x] - write a script to split the data into individual csv files
       the script will get an input of (from time, to time) and will write the csv files to disc.
        _this script writing is on hold because of encoding error while attempting to write individual veredict00.json line into sole 
          json file_
- [x] - write a python script with keywords for each and every category    
         _On hold because of our decision of using classifier_  
- [x] - Load the data
- [x] - Clean the data
         _On hold because of our decision of using classifier_  
- [x] - Write a simple tokenizer

- [x]  Determine which python script to write to clean the data.  NO CLEANNING !
TOKENIZING Everything  or specific keywords, maybe BOTH ? see "Clean the data"

- [x] - Determine case category manually - Look for real-estate but sort others as well
    _That process takes a lot of time- realestate cases seem to be less significant on the examined results so far_
    _A lot of ruling decision are of arrest extension or Adminstrative such as "case moved to.." or "Discussion postponed".._
    **Less that 100 rulings examined so far and we are very far away from 100 ruling cases to work on**

Various scripts has been written to ease that process:
- Splitter
- ID Extractor
- Get ruling summary
- Check if input has keywords
Tasks:
- [x] Write a script to move files of ruling containing specific keywords
- [x] Look over results manually

Something to check:
Why we have only 102,670 extracted ID's when the are 212,348 veredict json files - SOLVED
 
_Whats has been done ? 
- use of CountVectorizer to check words instances
- plotting the results - LTR to RTL not present by default
- retuning custom tokenizer with REGEX to accept only hebrew letters and non single-char strings
  - this raise an issues with sorting the dictionary for some reason

- [x] - Write a script to determine earliest and latest veredicts exists
_as of 08/02/2021 the script yields_
_earliest - 06/01/1997_
_latest - 09/12/2020_

ATTENTION
_All of the Tasks are postponed due to .xls file that has been delivered
_SEE ISSUE: ML Classification_

Tasks:
- [x] - Move 50 real realestate rulings to "true" folder
- [x] - Move 50 NOT realestate related ruling to "false"
- [x] - Load to DF and make sure no NULL values are present 
- [x] - Load and initialize those DFs to CategorialNB
- [x] - Load and initialize those DFs to SVM
- [x] - plot results and check confusion matrix
- [x] - Examine results and possibly retune the algorithm
- [x] - Move all the needed code to a python class - recheck styling and conventions before.
         Check for elegant way to comment everything properly

--WAY WAY AHEAD--   
Determine if the sue./defense won/lost
Check sue start/end - Keep court discussions in mind - (coupled to the name of the case with '-' ?)
-----Look for other collectable insights "on the fly" while manually checking-----
