### ISSUE TITLE
Upgrade Elastic version 5.5.6 -> 7.x

### ISSUE THREAD

**Issue by Immanuelbh** [Immanuelbh/HebrewCourtVerdictsAnalyzer#3]
## Goals
- [x] Upgrade all relevant plugins
- [x] Run Elastic stack with Hebmorph plugin on version 7.x (**planned 7.10.2**)
- [x] Run HCVA on ES 7.x

## Progress
- Created framework to transition from 5.5.6 to 7.x - [HCVA-env-set-up](https://github.com/Immanuelbh/HCVA-env-set-up)
- Created example plugin running on ES version 7.10.2

## Planned
- Update "elasticsearch-analysis-hebrew-5.5.3" zip
  - analysis-hebrew-5.5.3
  - hebmorph-lucene-6.6.0

**Comment by Immanuelbh** [comment]
Rolling upgrades by Elasticsearch - [link](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/rolling-upgrades.html)
